"""esquema inicial

ID de revision: 72591e694a93
Revision anterior: 
Fecha: 2026-09-04 15:57:11.332469+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '72591e694a93'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('modulo', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permisos'))
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_index(op.f('ix_permisos_modulo'), 'permisos', ['modulo'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('es_sistema', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_codigo'), 'roles', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('proveedor', sa.String(length=16), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=256), nullable=True),
    sa.Column('identificador_externo', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('es_superusuario', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_contrasena', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.SmallInteger(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(proveedor = 'LOCAL' AND hash_contrasena IS NOT NULL) OR (proveedor <> 'LOCAL' AND identificador_externo IS NOT NULL)", name=op.f('ck_usuarios_credencial_coherente_con_proveedor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('proveedor', 'identificador_externo', name='uq_identidad_externa')
    )
    op.create_index('ix_usuarios_activo', 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('consulta_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periodo_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completados', sa.Integer(), nullable=False),
    sa.Column('fallidos', sa.Integer(), nullable=False),
    sa.Column('omitidos', sa.Integer(), nullable=False),
    sa.Column('esperando_desafio', sa.Integer(), nullable=False),
    sa.Column('fallos_consecutivos', sa.SmallInteger(), nullable=False),
    sa.Column('pausado_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('motivo_pausa', sa.Text(), nullable=True),
    sa.Column('proxima_ejecucion_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_actividad_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('fk_consulta_jobs_creado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consulta_jobs'))
    )
    op.create_index('ix_jobs_estado', 'consulta_jobs', ['estado'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('tipo_documento', sa.String(length=16), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('email_institucional', sa.String(length=254), nullable=True),
    sa.Column('email_personal', sa.String(length=254), nullable=True),
    sa.Column('telefono', sa.String(length=32), nullable=True),
    sa.Column('tipo_vinculacion', sa.String(length=24), nullable=False),
    sa.Column('unidad', sa.String(length=160), nullable=True),
    sa.Column('cargo', sa.String(length=160), nullable=True),
    sa.Column('codigo_empleado', sa.String(length=40), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('ultima_consulta_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_consulta_estado', sa.String(length=24), nullable=True),
    sa.Column('ultima_consulta_exitosa_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_consultas', sa.Integer(), nullable=False),
    sa.Column('titulos_registrados', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(cedula) = 10', name=op.f('ck_personas_cedula_diez_digitos')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('fk_personas_creado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personas'))
    )
    op.create_index('ix_personas_busqueda', 'personas', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_index(op.f('ix_personas_cedula'), 'personas', ['cedula'], unique=True)
    op.create_index('ix_personas_cobertura', 'personas', ['activo', 'ultima_consulta_en'], unique=False)
    op.create_index(op.f('ix_personas_codigo_empleado'), 'personas', ['codigo_empleado'], unique=False)
    op.create_index(op.f('ix_personas_email_institucional'), 'personas', ['email_institucional'], unique=False)
    op.create_index(op.f('ix_personas_ultima_consulta_en'), 'personas', ['ultima_consulta_en'], unique=False)
    op.create_index('ix_personas_unidad', 'personas', ['unidad'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name=op.f('fk_rol_permisos_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_rol_permisos_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name=op.f('pk_rol_permisos'))
    )
    op.create_table('tokens_refresco',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hash_token', sa.String(length=128), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revocado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reemplazado_por', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('direccion_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_tokens_refresco_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens_refresco'))
    )
    op.create_index(op.f('ix_tokens_refresco_expira_en'), 'tokens_refresco', ['expira_en'], unique=False)
    op.create_index(op.f('ix_tokens_refresco_hash_token'), 'tokens_refresco', ['hash_token'], unique=True)
    op.create_index('ix_tokens_usuario_activos', 'tokens_refresco', ['usuario_id', 'revocado_en'], unique=False)
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_usuario_roles_rol_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_roles_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id', name=op.f('pk_usuario_roles'))
    )
    op.create_table('consulta_job_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('programado_para', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos', sa.SmallInteger(), nullable=False),
    sa.Column('ultimo_log_id', sa.UUID(), nullable=True),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.Column('desafio_id', sa.String(length=128), nullable=True),
    sa.Column('procesado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['consulta_jobs.id'], name=op.f('fk_consulta_job_items_job_id_consulta_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_consulta_job_items_persona_id_personas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consulta_job_items')),
    sa.UniqueConstraint('job_id', 'persona_id', name='uq_persona_por_job')
    )
    op.create_index('ix_items_cola', 'consulta_job_items', ['job_id', 'estado', 'programado_para'], unique=False)
    op.create_index('ix_items_desafio', 'consulta_job_items', ['desafio_id'], unique=False)
    op.create_table('consulta_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=24), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('proveedor', sa.String(length=32), nullable=False),
    sa.Column('intento', sa.SmallInteger(), nullable=False),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('titulos_encontrados', sa.SmallInteger(), nullable=False),
    sa.Column('titulos_nuevos', sa.SmallInteger(), nullable=False),
    sa.Column('titulos_actualizados', sa.SmallInteger(), nullable=False),
    sa.Column('titulos_retirados', sa.SmallInteger(), nullable=False),
    sa.Column('cambios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('tipo_error', sa.String(length=80), nullable=True),
    sa.Column('codigo_http', sa.SmallInteger(), nullable=True),
    sa.Column('respuesta_cruda', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ejecutado_por', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ejecutado_por'], ['usuarios.id'], name=op.f('fk_consulta_logs_ejecutado_por_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['consulta_jobs.id'], name=op.f('fk_consulta_logs_job_id_consulta_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_consulta_logs_persona_id_personas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consulta_logs'))
    )
    op.create_index(op.f('ix_consulta_logs_cedula'), 'consulta_logs', ['cedula'], unique=False)
    op.create_index('ix_logs_estado_fecha', 'consulta_logs', ['estado', 'iniciado_en'], unique=False)
    op.create_index('ix_logs_job', 'consulta_logs', ['job_id'], unique=False)
    op.create_index('ix_logs_persona_fecha', 'consulta_logs', ['persona_id', 'iniciado_en'], unique=False)
    op.create_index('ix_logs_ventana', 'consulta_logs', ['iniciado_en'], unique=False)
    op.create_table('titulos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('denominacion', sa.String(length=400), nullable=False),
    sa.Column('institucion', sa.String(length=300), nullable=False),
    sa.Column('nivel', sa.String(length=24), nullable=False),
    sa.Column('numero_registro', sa.String(length=64), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('fecha_graduacion', sa.Date(), nullable=True),
    sa.Column('area_conocimiento', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=64), nullable=False),
    sa.Column('observacion_registro', sa.Text(), nullable=True),
    sa.Column('origen', sa.String(length=16), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('huella', sa.String(length=32), nullable=False),
    sa.Column('datos_crudos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visto_primera_vez_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visto_ultima_vez_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retirado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('verificado_por', sa.UUID(), nullable=True),
    sa.Column('verificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_titulos_persona_id_personas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verificado_por'], ['usuarios.id'], name=op.f('fk_titulos_verificado_por_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_titulos')),
    sa.UniqueConstraint('persona_id', 'huella', name='uq_titulo_por_persona')
    )
    op.create_index(op.f('ix_titulos_huella'), 'titulos', ['huella'], unique=False)
    op.create_index('ix_titulos_institucion', 'titulos', ['institucion'], unique=False)
    op.create_index('ix_titulos_nivel_estado', 'titulos', ['nivel', 'estado'], unique=False)
    op.create_index(op.f('ix_titulos_persona_id'), 'titulos', ['persona_id'], unique=False)
    op.create_index('ix_titulos_registro', 'titulos', ['numero_registro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titulos_registro', table_name='titulos')
    op.drop_index(op.f('ix_titulos_persona_id'), table_name='titulos')
    op.drop_index('ix_titulos_nivel_estado', table_name='titulos')
    op.drop_index('ix_titulos_institucion', table_name='titulos')
    op.drop_index(op.f('ix_titulos_huella'), table_name='titulos')
    op.drop_table('titulos')
    op.drop_index('ix_logs_ventana', table_name='consulta_logs')
    op.drop_index('ix_logs_persona_fecha', table_name='consulta_logs')
    op.drop_index('ix_logs_job', table_name='consulta_logs')
    op.drop_index('ix_logs_estado_fecha', table_name='consulta_logs')
    op.drop_index(op.f('ix_consulta_logs_cedula'), table_name='consulta_logs')
    op.drop_table('consulta_logs')
    op.drop_index('ix_items_desafio', table_name='consulta_job_items')
    op.drop_index('ix_items_cola', table_name='consulta_job_items')
    op.drop_table('consulta_job_items')
    op.drop_table('usuario_roles')
    op.drop_index('ix_tokens_usuario_activos', table_name='tokens_refresco')
    op.drop_index(op.f('ix_tokens_refresco_hash_token'), table_name='tokens_refresco')
    op.drop_index(op.f('ix_tokens_refresco_expira_en'), table_name='tokens_refresco')
    op.drop_table('tokens_refresco')
    op.drop_table('rol_permisos')
    op.drop_index('ix_personas_unidad', table_name='personas')
    op.drop_index(op.f('ix_personas_ultima_consulta_en'), table_name='personas')
    op.drop_index(op.f('ix_personas_email_institucional'), table_name='personas')
    op.drop_index(op.f('ix_personas_codigo_empleado'), table_name='personas')
    op.drop_index('ix_personas_cobertura', table_name='personas')
    op.drop_index(op.f('ix_personas_cedula'), table_name='personas')
    op.drop_index('ix_personas_busqueda', table_name='personas', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_table('personas')
    op.drop_index('ix_jobs_estado', table_name='consulta_jobs')
    op.drop_table('consulta_jobs')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index('ix_usuarios_activo', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_codigo'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_modulo'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
