"""distributivo docente y catalogos

ID de revision: ae3efae2f274
Revision anterior: 72591e694a93
Fecha: 2026-09-11 01:35:31.858780+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ae3efae2f274'
down_revision: str | None = '72591e694a93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_carreras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_carreras')),
    sa.UniqueConstraint('codigo', name='uq_cat_carreras_codigo')
    )
    op.create_index('ix_cat_carreras_activo_orden', 'cat_carreras', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_carreras_busqueda', 'cat_carreras', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_categorias',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_categorias')),
    sa.UniqueConstraint('codigo', name='uq_cat_categorias_codigo')
    )
    op.create_index('ix_cat_categorias_activo_orden', 'cat_categorias', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_categorias_busqueda', 'cat_categorias', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_dedicaciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_dedicaciones')),
    sa.UniqueConstraint('codigo', name='uq_cat_dedicaciones_codigo')
    )
    op.create_index('ix_cat_dedicaciones_activo_orden', 'cat_dedicaciones', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_dedicaciones_busqueda', 'cat_dedicaciones', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_facultades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_facultades')),
    sa.UniqueConstraint('codigo', name='uq_cat_facultades_codigo')
    )
    op.create_index('ix_cat_facultades_activo_orden', 'cat_facultades', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_facultades_busqueda', 'cat_facultades', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_generos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_generos')),
    sa.UniqueConstraint('codigo', name='uq_cat_generos_codigo')
    )
    op.create_index('ix_cat_generos_activo_orden', 'cat_generos', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_generos_busqueda', 'cat_generos', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_niveles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_niveles')),
    sa.UniqueConstraint('codigo', name='uq_cat_niveles_codigo')
    )
    op.create_index('ix_cat_niveles_activo_orden', 'cat_niveles', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_niveles_busqueda', 'cat_niveles', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_paos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_paos')),
    sa.UniqueConstraint('codigo', name='uq_cat_paos_codigo')
    )
    op.create_index('ix_cat_paos_activo_orden', 'cat_paos', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_paos_busqueda', 'cat_paos', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_programas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_programas')),
    sa.UniqueConstraint('codigo', name='uq_cat_programas_codigo')
    )
    op.create_index('ix_cat_programas_activo_orden', 'cat_programas', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_programas_busqueda', 'cat_programas', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_sedes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_sedes')),
    sa.UniqueConstraint('codigo', name='uq_cat_sedes_codigo')
    )
    op.create_index('ix_cat_sedes_activo_orden', 'cat_sedes', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_sedes_busqueda', 'cat_sedes', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_tipos_titulo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_tipos_titulo')),
    sa.UniqueConstraint('codigo', name='uq_cat_tipos_titulo_codigo')
    )
    op.create_index('ix_cat_tipos_titulo_activo_orden', 'cat_tipos_titulo', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_tipos_titulo_busqueda', 'cat_tipos_titulo', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_titularidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_titularidades')),
    sa.UniqueConstraint('codigo', name='uq_cat_titularidades_codigo')
    )
    op.create_index('ix_cat_titularidades_activo_orden', 'cat_titularidades', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_titularidades_busqueda', 'cat_titularidades', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('cat_titulos_profesionales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=320), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_titulos_profesionales')),
    sa.UniqueConstraint('codigo', name='uq_cat_titulos_profesionales_codigo')
    )
    op.create_index('ix_cat_titulos_profesionales_activo_orden', 'cat_titulos_profesionales', ['activo', 'orden'], unique=False)
    op.create_index('ix_cat_titulos_profesionales_busqueda', 'cat_titulos_profesionales', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_table('docentes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('es_cedula', sa.Boolean(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('clave_busqueda', sa.Text(), nullable=False),
    sa.Column('genero_id', sa.UUID(), nullable=True),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['cat_generos.id'], name=op.f('fk_docentes_genero_id_cat_generos'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_docentes_persona_id_personas'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_docentes')),
    sa.UniqueConstraint('identificacion', name='uq_docentes_identificacion')
    )
    op.create_index('ix_docentes_activo', 'docentes', ['activo'], unique=False)
    op.create_index('ix_docentes_busqueda', 'docentes', ['clave_busqueda'], unique=False, postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.create_index(op.f('ix_docentes_persona_id'), 'docentes', ['persona_id'], unique=False)
    op.create_table('distributivo',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('pao_id', sa.UUID(), nullable=False),
    sa.Column('facultad_id', sa.UUID(), nullable=False),
    sa.Column('carrera_id', sa.UUID(), nullable=False),
    sa.Column('programa_id', sa.UUID(), nullable=True),
    sa.Column('sede_id', sa.UUID(), nullable=True),
    sa.Column('nivel_id', sa.UUID(), nullable=True),
    sa.Column('titularidad_id', sa.UUID(), nullable=True),
    sa.Column('dedicacion_id', sa.UUID(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('tipo_titulo_id', sa.UUID(), nullable=True),
    sa.Column('asignatura', sa.String(length=400), nullable=True),
    sa.Column('horas_docencia', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horas_gestion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horas_investigacion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('horas_vinculacion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_docencia', sa.Float(), nullable=False),
    sa.Column('total_gestion', sa.Float(), nullable=False),
    sa.Column('total_investigacion', sa.Float(), nullable=False),
    sa.Column('total_vinculacion', sa.Float(), nullable=False),
    sa.Column('total_horas', sa.Float(), nullable=False),
    sa.Column('medida', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_horas >= 0', name=op.f('ck_distributivo_total_horas_no_negativo')),
    sa.ForeignKeyConstraint(['carrera_id'], ['cat_carreras.id'], name=op.f('fk_distributivo_carrera_id_cat_carreras'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['categoria_id'], ['cat_categorias.id'], name=op.f('fk_distributivo_categoria_id_cat_categorias'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('fk_distributivo_creado_por_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dedicacion_id'], ['cat_dedicaciones.id'], name=op.f('fk_distributivo_dedicacion_id_cat_dedicaciones'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name=op.f('fk_distributivo_docente_id_docentes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facultad_id'], ['cat_facultades.id'], name=op.f('fk_distributivo_facultad_id_cat_facultades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nivel_id'], ['cat_niveles.id'], name=op.f('fk_distributivo_nivel_id_cat_niveles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pao_id'], ['cat_paos.id'], name=op.f('fk_distributivo_pao_id_cat_paos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['programa_id'], ['cat_programas.id'], name=op.f('fk_distributivo_programa_id_cat_programas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sede_id'], ['cat_sedes.id'], name=op.f('fk_distributivo_sede_id_cat_sedes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_titulo_id'], ['cat_tipos_titulo.id'], name=op.f('fk_distributivo_tipo_titulo_id_cat_tipos_titulo'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['titularidad_id'], ['cat_titularidades.id'], name=op.f('fk_distributivo_titularidad_id_cat_titularidades'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributivo')),
    sa.UniqueConstraint('docente_id', 'pao_id', 'carrera_id', 'sede_id', name='uq_distributivo_docente_pao_carrera_sede', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_distributivo_carrera', 'distributivo', ['carrera_id'], unique=False)
    op.create_index('ix_distributivo_docente_pao', 'distributivo', ['docente_id', 'pao_id'], unique=False)
    op.create_index('ix_distributivo_pao_carrera', 'distributivo', ['pao_id', 'carrera_id'], unique=False)
    op.create_index('ix_distributivo_pao_facultad', 'distributivo', ['pao_id', 'facultad_id'], unique=False)
    op.create_index(op.f('ix_distributivo_total_horas'), 'distributivo', ['total_horas'], unique=False)
    op.create_table('docente_titulos',
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('titulo_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], name=op.f('fk_docente_titulos_docente_id_docentes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['titulo_id'], ['cat_titulos_profesionales.id'], name=op.f('fk_docente_titulos_titulo_id_cat_titulos_profesionales'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docente_id', 'titulo_id', name=op.f('pk_docente_titulos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('docente_titulos')
    op.drop_index(op.f('ix_distributivo_total_horas'), table_name='distributivo')
    op.drop_index('ix_distributivo_pao_facultad', table_name='distributivo')
    op.drop_index('ix_distributivo_pao_carrera', table_name='distributivo')
    op.drop_index('ix_distributivo_docente_pao', table_name='distributivo')
    op.drop_index('ix_distributivo_carrera', table_name='distributivo')
    op.drop_table('distributivo')
    op.drop_index(op.f('ix_docentes_persona_id'), table_name='docentes')
    op.drop_index('ix_docentes_busqueda', table_name='docentes', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_docentes_activo', table_name='docentes')
    op.drop_table('docentes')
    op.drop_index('ix_cat_titulos_profesionales_busqueda', table_name='cat_titulos_profesionales', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_titulos_profesionales_activo_orden', table_name='cat_titulos_profesionales')
    op.drop_table('cat_titulos_profesionales')
    op.drop_index('ix_cat_titularidades_busqueda', table_name='cat_titularidades', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_titularidades_activo_orden', table_name='cat_titularidades')
    op.drop_table('cat_titularidades')
    op.drop_index('ix_cat_tipos_titulo_busqueda', table_name='cat_tipos_titulo', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_tipos_titulo_activo_orden', table_name='cat_tipos_titulo')
    op.drop_table('cat_tipos_titulo')
    op.drop_index('ix_cat_sedes_busqueda', table_name='cat_sedes', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_sedes_activo_orden', table_name='cat_sedes')
    op.drop_table('cat_sedes')
    op.drop_index('ix_cat_programas_busqueda', table_name='cat_programas', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_programas_activo_orden', table_name='cat_programas')
    op.drop_table('cat_programas')
    op.drop_index('ix_cat_paos_busqueda', table_name='cat_paos', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_paos_activo_orden', table_name='cat_paos')
    op.drop_table('cat_paos')
    op.drop_index('ix_cat_niveles_busqueda', table_name='cat_niveles', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_niveles_activo_orden', table_name='cat_niveles')
    op.drop_table('cat_niveles')
    op.drop_index('ix_cat_generos_busqueda', table_name='cat_generos', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_generos_activo_orden', table_name='cat_generos')
    op.drop_table('cat_generos')
    op.drop_index('ix_cat_facultades_busqueda', table_name='cat_facultades', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_facultades_activo_orden', table_name='cat_facultades')
    op.drop_table('cat_facultades')
    op.drop_index('ix_cat_dedicaciones_busqueda', table_name='cat_dedicaciones', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_dedicaciones_activo_orden', table_name='cat_dedicaciones')
    op.drop_table('cat_dedicaciones')
    op.drop_index('ix_cat_categorias_busqueda', table_name='cat_categorias', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_categorias_activo_orden', table_name='cat_categorias')
    op.drop_table('cat_categorias')
    op.drop_index('ix_cat_carreras_busqueda', table_name='cat_carreras', postgresql_using='gin', postgresql_ops={'clave_busqueda': 'gin_trgm_ops'})
    op.drop_index('ix_cat_carreras_activo_orden', table_name='cat_carreras')
    op.drop_table('cat_carreras')
    # ### end Alembic commands ###
